Algoritmo "20_lista1"

Var
    num1, num2, num3, num4, num5, media: real

Inicio
    escreva("Primeiro número: ")
    leia(num1)
    escreva("Segundo número: ")
    leia(num2)
    escreva("Terceiro número: ")
    leia(num3)
    escreva("Quarto número: ")
    leia(num4)
    escreva("Quinto número: ")
    leia(num5)
    
    media <- ((num1*2)+(num2*4)+(num3*2)+(num4*5)+(num5*3))/5
    
    escreva("Média Ponderada: ",media)

Fimalgoritmo